test_split: validation
doc_to_messages: !function utils.charxiv_reasoning_doc_to_messages_cot
doc_to_text: !function utils.charxiv_reasoning_doc_to_text_cot
doc_to_target: "reasoning_a"
include: _default_template_yaml
task: charxiv_val_reasoning
process_results: !function utils.charxiv_reasoning_process_results
metric_list:
  - metric: reasoning_acc
    aggregation: !function utils.charxiv_reasoning_aggregate_results
    higher_is_better: true