task: "step2_audio_paralinguistic_voice_styles"
test_split: voice_styles
include: _default_template_yaml
metric_list:
  - metric: semantic_match
    aggregation: !function utils.semantic_match_aggregate
    higher_is_better: true
